import { applyMiddleware, createStore } from 'redux';
import appReducer from './reducers';
import { createLogger } from 'redux-logger';
// import { createSagaMiddleware } from 'redux-saga';
import thunk from 'redux-thunk';
const log = createLogger();
// const sagaMiddleware = createSagaMiddleware();
const store = createStore(appReducer, applyMiddleware(thunk, log));
// sagaMiddleware.run();
export default store;
